version: "3"

services:
  # Django app
  app:
    build:
      context: .
      dockerfile: ./services/app/Dockerfile
    command: dev
    ports:
      - 8000:8000
      - 8001:8001
    volumes:
      - ./app:/usr/src/app
    environment:
      - PORT=8000
      - WSGI_MODULE=config.wsgi:application
    env_file:
      - .env

  web:
    build:
      context: ./
      dockerfile: ./services/nginx/Dockerfile
    ports:
      - 80:80
    depends_on:
      - app
