# Generated by Django 2.2.9 on 2020-01-10 16:08

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='banner_blurb',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
