# Generated by Django 2.2.9 on 2020-01-11 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20200111_1527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postpage',
            options={'ordering': ['first_published_at']},
        ),
        migrations.RemoveField(
            model_name='postpage',
            name='created',
        ),
        migrations.RemoveField(
            model_name='postpage',
            name='modified',
        ),
    ]
