# Generated by Django 2.2.9 on 2020-01-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_auto_20200126_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpage',
            name='seo_description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
