# Generated by Django 2.2.9 on 2022-02-21 02:40

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
from wagtail.core.rich_text import RichText


def convert_to_streamfield(apps, schema_editor):
    PostPage = apps.get_model("frontend", "PostPage")
    for page in PostPage.objects.all():
        if page.body.raw_text and not page.body:
            page.body = [("rich_text", RichText(page.body.raw_text))]
            page.save()


def convert_to_richtext(apps, schema_editor):
    PostPage = apps.get_model("frontend", "PostPage")
    for page in PostPage.objects.all():
        if page.body.raw_text is None:
            raw_text = "".join(
                [
                    child.value.source
                    for child in page.body
                    if child.block_type == "rich_text"
                ]
            )
            page.body = raw_text
            page.save()


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0007_postpage_seo_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="portfolioitem", options={"ordering": ["sort_order"]},
        ),
        migrations.AlterField(
            model_name="postpage",
            name="body",
            field=wagtail.core.fields.StreamField(
                [
                    ("heading", wagtail.core.blocks.CharBlock(classname="full title")),
                    (
                        "rich_text",
                        wagtail.core.blocks.RichTextBlock(
                            features=[
                                "h4",
                                "bold",
                                "italic",
                                "underline",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                                "code",
                                "blockquote",
                            ]
                        ),
                    ),
                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                ]
            ),
        ),
        migrations.RunPython(convert_to_streamfield, convert_to_richtext,),
    ]
